### ISSUE TITLE
Change User Admin profile picture

### ISSUE THREAD

**Issue by romquenin** [causefx/Organizr#1041]
Hello i can't find where to change the profile picture. Do you have an on idea where to search.

![screenshot_2019-01-23 organizr v2](https://user-images.githubusercontent.com/34734431/51620320-6253dd80-1f32-11e9-9ad4-2c91aa2c6d6c.png)

Thanks.

**Comment by causefx** [comment]
it uses gravatar.

https://en.gravatar.com/

**Comment by romquenin** [comment]
Thanks @causefx.

**Comment by CollinChaffin** [comment]
@causefx The issue with this is that gravatar has restrictions on the email addresses used that are absolute show-stoppers for many.  For starters, any address that limits inbound email and cannot even get the very 1st "confirmation" email, cannot even use it.  This is why to this day gravatar avatars do not show across all of Gitkraken and other tools that force the use of the "noreply" github address (and ties your login to it) because the address cannot even be verified for use.

Not to mention the privacy concerns that prevent many now from touching gravatar (leaking network access with your email addresses constantly just to refresh an avatar without even asking the user's consent or notifying them first)!

I know it's a closed issue, but food for thought as to reasons to reconsider perhaps even just adding other local avatar options.  The code to load a local jpg/png isn't much in any language and in most cases is already publically posted.
