### ISSUE TITLE
No Fullscreen on mobile and tv browsers in emby tab

### ISSUE THREAD

**Issue by Dazzler1985** [causefx/Organizr#1191]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
When i open organizr on my mobile or on a smart tv browser and go to my emby tab and i play a video there is no fullscreen button in the player or any controls . When i open emby directly without organizr all controls and fullscreen mode are there . On desktop pc's there is no problem.

<hr>

##### Reproduction Steps:
Login on an android phone and open emby tab. or login on a smart tv browser.

**Comment by tronyx** [comment]
Do you have Emby setup with a reverse proxy and that's what is in your Tab URL in Organizr or is it just the local IP:PORT? If it's a reverse proxy, there's most likely a missing header that's not loading everything properly and if it's local, it's most likely due to Emby being iFramed and something isn't being allowed through the iFrame.

**Comment by causefx** [comment]
I'm not sure this is something i can fix
