### ISSUE TITLE
2.0.307 - LDAP password is not changed during password change

### ISSUE THREAD

**Issue by shocker2** [causefx/Organizr#1245]
If you are using only LDAP backend and change the user password via Organizr, there is a success message that this has been changed, but the password is not changed in LDAP.

**Comment by tronyx** [comment]
Organizr cannot write changes to the LDAP Server. The point of LDAP is you change it within the LDAP Server and then any Servers/Applications using the LDAP Server will recognize the changes when authentication is performed.

**Comment by shocker2** [comment]
> Organizr cannot write changes to the LDAP Server. The point of LDAP is you change it within the LDAP Server and then any Servers/Applications using the LDAP Server will recognize the changes when authentication is performed.

Thank you for the feedback!

Then it would be nice to disable the change password option if the backend is set to LDAP in order to not create confusion.

**Comment by tronyx** [comment]
The ability to have an LDAP account for Organizr that has admin access is so that this operation can be performed successfully is still something that is being worked on (with no ETA) so it's much easier for people to understand the basics of LDAP and know that changing the actual LDAP account password through Organizr is not currently possible.

**Comment by shocker2** [comment]
> The ability to have an LDAP account for Organizr that has admin access is so that this operation can be performed successfully is still something that is being worked on (with no ETA) so it's much easier for people to understand the basics of LDAP and know that changing the actual LDAP account password through Organizr is not currently possible.

I agre that it's easy to understand for admin, but it would be nice for users to just add a "disabled" check in the fields.
Or can I hide the change password box via a custom CSS?

**Comment by tronyx** [comment]
Not sure about the CSS so you'd have to explore the elements and see if it's possible. @causefx would need to chime in about disabling the ability for users to change their passwords if a different backend is chosen.

**Comment by causefx** [comment]
I will only disable if backend is set to LDAP only

**Comment by shocker2** [comment]
> I will only disable if backend is set to LDAP only

Awasome, thanks! Also disable the reset password/signup functionality as they will not work.

**Comment by tronyx** [comment]
@causefx I believe I remember seeing something for this in a commit, but cannot remember. Could you confirm?

**Comment by sduensin** [comment]
> I will only disable if backend is set to LDAP only

I'd really like an option to disable it instead.  I'm using mixed backends so I can still log in as admin if I'm having ldap issues.

**Comment by ibracorp** [comment]
I've set it to backend only and it still shows a reset password option on login screen.

This kind of breaks the point of LDAP because it should be single source of truth. However I noticed after using the reset function it allowed me to use both the newly generated and the LDAP password to log in. 

Having the option to disable OR change the link to our own (like Nextcloud) would be ideal.

**Comment by causefx** [comment]
recover password can now be disabled in dev branch
