### ISSUE TITLE
Nginx Auth and Sickrage

### ISSUE THREAD

**Issue by stanthewizzard** [causefx/Organizr#1248]
###### Operating System: Ubuntu 19.04
<hr>

##### Problem Description:
Everything works fine for Sickrage BUT when I want to add a show I get an error 500.
thanks for help
<hr>

**Comment by tronyx** [comment]
Well, we're going to need more information here since you basically provided none. Are Nginx, Organizr, and Sickrage installed natively or within Docker containers? How do you have the Auth enabled? Are you experiencing this when using Sickrage through an iFrame in Organizr or just in general? Have you looked at the Nginx, PHP, Organizr, or Sickrage logs to try and see what the 500 error may be indicating?

It sounds like a missing header parameter or something that's causing the action of adding a show to throw the 500 error. Are you using custom error pages through Organizr? Do you have the `proxy_intercept_errors` Nginx parameter set to `on` for your Sickrage reverse proxy (if you're using one)?

**Comment by stanthewizzard** [comment]
well
same VM
no docker

Auth in nginx
##  Organizr auth direct
	location ~ /auth-(.*) {
		internal;
		rewrite ^/auth-(.*) /api/?v1/auth&group=$1;
	}

##  Organizr auth direct sub
	location ~ ^/auth-(.*) {
   	## Has to be local ip or local DNS name
    proxy_pass https://grabbing2.sdskh.com/api/?v1/auth&group=$1;
   	proxy_pass_request_body off;
   	proxy_set_header Content-Length "";

nothing in log

no custo page

no for proxy_intercept_errors ...will it populate the log with errors ? (this one is new for me)

Thanks for your help :)

**Comment by Xenocell12** [comment]
@stanthewizzard 

You'll need to auth exclude URL starting at /addshows

Example below. However, this is for subfolder configuration. The key is to exclude addShows. This will also allow you to add existing.

location /medusarage/addShows { auth_request off;
                proxy_pass http://192.168.1.79:5050/medusarage/addShows;
				}

Being as I was concerned about security as long as you don't exclude beyond addshows it will be basically broken to outsiders as everything to make this menu work get's 401'ed to death. You will see in your console.

The reason why this doesn't work from my understanding is the Python Web Server is doing many internal redirects and with the auth block in the proxy the app doesn't behave well. This affects all "sickrage" forks.

**Comment by stanthewizzard** [comment]
OK done (didn't thing to that ...I'm dumb)
It works
It also works for sabnzbd and RSS grabbing (btw and off topic)

Thanks @Xenocell12
