### ISSUE TITLE
[Feature Request] Auto Accept Plex Invites when Using Organizr Invites?

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [causefx/Organizr#1306]
So, when you send an invite out to someone through the Plex interface it generates a direct accept URL, were the server owner can give the person being referred the URL, and he/she can go to the URL sign in and have the library automatically added.

So, I'm wondering if it's possible to grab that url, server side, pass the login info the user provided when using the invite code for Organizr to Plex and auto accept that invite? This would cut out the extra step of the individual accepting it through Plex.tv and then coming back to Organizr. Especially useful for users who don't know how Plex works or for the lazies.

I'm guessing this isn't gonna be possible but, just throwing it out there.

**Comment by causefx** [comment]
don't think this is possible atm....  i think we can only do this if you know the users plex username and password to generate a token.

**Comment by zmike808** [comment]
I realize this is an old issue, but I actually had/have this working on v1 of the Organizr API, haven't deep dove into the new v2 API overhaul yet so I've been camping out on 2.0.650. 

Think it will only work for freshly created plex accounts however, but not 100% sure. I went and removed the option for "i have a plex account" since I wanted to make the process as simple as possible, and I only use organizr inviting for people who have no plex account already xD
