### ISSUE TITLE
Unable to rearrange tabs on iPad

### ISSUE THREAD

**Issue by danielhelmstedt** [causefx/Organizr#1333]
###### Operating System: Ubuntu
<hr>

##### Problem Description:

I’m unable to rearrange tabs on my iPad, as the page just scrolls instead of grabbing the ☰.
<hr>

##### Reproduction Steps:

Attempt to rearrange tabs on an iOS device using Safari
<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
Hmmmm - not sure what I want to do with this.  I may add arrows - let me see what people think/want

**Comment by danielhelmstedt** [comment]
Unfortunately I know nothing about PHP (I’m assuming this is a PHP issue?), but just wanted to add that it also affects the Rearrange Home Screen Items page. If arrows seem like a way forward, it all for it!

**Comment by Tosko4** [comment]
@causefx I think it’s a low priority one, but I am mostly on my ipad/iphone and got org now as my default home page.

When I need to rearrange, it would require me to go to the desktop because the drag and drop feature is not touch screen friendly. 

Low priority: because I think one does not rearrange that often. But it would be nice to have indeed. So I upvote this feature request.

**Comment by causefx** [comment]
@danielhelmstedt @Tosko4 fixed in dev - master will be pushed Friday
