### ISSUE TITLE
Question: Latest or php-fpm

### ISSUE THREAD

**Issue by zilexa** [causefx/Organizr#1346]
###### Operating System: Ubuntu 19.10, Intel Core i3, 8GB RAM. 

<hr>

##### Problem Description:
Running everything via Docker, I just realised I used an onofficial old docker image. Now that I want to use the official Organizrv2 I don't understand whether I should use Latest or php-fpm. I just want the most lightweight version that runs swiftly and I haven't used Organizr before. 

<hr>

**Comment by Roxedus** [comment]
The description for the container describes it nicely:

* The latest tag will get you the original Organizr v2 image.
* The php-fpm tag includes the implementation of PHP-FPM within the container instead of the default FastCGI. PHP-FPM is much more efficient, especially in terms of memory.

There is no extra packages in the php-fpm variant, its the same software.
There *may* be a slight overhead with fpm, but its minimal.

**Comment by zilexa** [comment]
Thanks I'm going for the PHP-FPM!
