### ISSUE TITLE
Req: Allow Middle-click to open in new tab

### ISSUE THREAD

**Issue by jscottelblein** [causefx/Organizr#1474]
Small request, would it be possible to add in middle mouse clicking to open a service in a new tab?

That's the normal link behavior in my browsers; currently for example, when ctrl+clicking say, NZBHydra in the services menu will do so, but middle click does nothing at all. Out of habit I always find myself first middle clicking a service, then thinking "oh yea, organizr doesn't do that", and then ctrl-clicking it.

Personally speaking, A lot of times I keep my right hand on the mouse, and rest my chin upon my left palm as I am looking over things, so it takes a ton of energy for my lazy arse to have to always lower my left hand back to the keyboard, and support the weight of my own head all by itself. Especially in the morning before I'm done with my coffee.  :P 

TIA!

**Comment by causefx** [comment]
does middle button do anything at all at the moment?

I dont have a middle button mouse to test

**Comment by jscottelblein** [comment]
> does middle button do anything at all at the moment?
> 
> I dont have a middle button mouse to test

Newp, nothing at all.

**Comment by Jerrk** [comment]
![](https://i.imgur.com/VwKuq2s.gif)
It does show an animation but it does not do anything other than that.

**Comment by jscottelblein** [comment]
> ![](https://camo.githubusercontent.com/3c3a3c7d43fbcfdbb8520202267a638a05b118c7/68747470733a2f2f692e696d6775722e636f6d2f56774b757132732e676966)
> It does show an animation but it does not do anything other than that.

Other than the hover-highlighting I don't even get that click animation on mine.

Maybe it has to do with our theme choices? Looks like you're using a diff theme than mine. I'm using the Organizr Dark theme.

**Comment by TomW1605** [comment]
i have had a quick look into this and it would be quit straight forward. there are 2 main things that would need changing.

the first thing is that each tab icon has an `onclick` action. this needs to be changed to an `onauxclick` action so that it catches middle clicks. i have not found where this needs to be changed but i doubt it will be hard for someone familiar with the project.

the other is a change to the tab loading JS. the tab icon `onclick` action calls the `tabActions` function. this needs to be changed to handle the middle click. the simplest way to do that is to add a condition to the ctrl+click if statement for the middle moues button. this would mean changing [this line](https://github.com/causefx/Organizr/blob/8a22b9fe8356c891828da0af494243b8d94d24f9/js/functions.js#L946) from `if(event.ctrlKey && !event.shiftKey && !event.altKey){` to `if((event.ctrlKey && !event.shiftKey && !event.altKey) || event.which==2){` (there might be a neater way to do this).

it will also now need to handle for right mouse click so that accessing a context menus does not trigger a tab change. this could be a simple as adding this `if(event.which!=1 && event.which!=2){` empty if statement before the open in new window one and changing that to an else if.

i have tested this by substituting the functions on an already loaded page and it works however i have not tested the changes in the backend.

let me know if you need more information or if i am way off on my idea.

**Comment by joshhazel** [comment]
I was just googling for how to do this too.  It is the only thing keeping me from using Organizr 100% ..  so, +1 if it can be implemented

**Comment by TomW1605** [comment]
@causefx any chance on getting a response to this?

**Comment by causefx** [comment]
please try the latest commit on dev to see if this worked, I don't have a mouse with middle button to test.
EDIT: Actually it does work - i mapped middle button to an alt button on my mouse.  It seems Edge doesn't recognize middle button for me, but I tried in Firefox and it worked.

**Comment by TomW1605** [comment]
that works great thanks for adding it.

**Comment by jscottelblein** [comment]
Working great, thanks!

**Comment by joshhazel** [comment]
Dumb question, how can i update my organizr to pick up the change?   I tried the built in Check for Updates > Install Update 2.1.183 but the middle click doesnt open a new tab  >_<  thanks

**Comment by causefx** [comment]
does it show that you are on 2.1.183 now tho?
clear cache?

**Comment by joshhazel** [comment]
![image](https://user-images.githubusercontent.com/1430324/106342285-e8176b80-6265-11eb-856c-140718ca5b2b.png)

Yeah, it shows 2.1.183, Cleared cache, 
but when middle clicking the middle mouse button on any of the tabs (sonarr, radarr) on the left side its not doing anything for me

**Comment by causefx** [comment]
what browser?

**Comment by joshhazel** [comment]
> what browser?
Chrome 88.0.4324.104, I also tried Edge 88.0.705.56

**Comment by causefx** [comment]
@TomW1605 @STaRDoGG what browsers are you guys using...?
I think it doesn't work for chromium based browsers...  I'll try to find a work around.

**Comment by TomW1605** [comment]
> @TomW1605 @STaRDoGG what browsers are you guys using...?
> I think it doesn't work for chromium based browsers... I'll try to find a work around.

i am using chrome v86.0.4240.198

**Comment by jscottelblein** [comment]
I just tested on 2.1.183 v2-Master (Docker):

- Chrome Version 88.0.4324.104 (Official Build) (64-bit)
- Edge Version 88.0.705.56 (Official build) (64-bit)
- Firefox 85.0 (64-bit)

All work fine

- Opera Version:73.0.3856.344

Gives me the "Quick Scroll" icon. I'm not sure if that's due to a setting in Opera or something though (I didn't look; I don't use Opera very often.)

**Comment by Jerrk** [comment]
i have an issue where middle clicking to open a new tab is creating an extra tab named javascript:void(0)
![](https://i.imgur.com/bN2yK2b.gif)

hopefully that can be fixed 😄 

Firefox nightly 96.0a1
Organizr 2.1.1140

**Comment by HalianElf** [comment]
> i have an issue where middle clicking to open a new tab is creating an extra tab named javascript:void(0) ![](https://camo.githubusercontent.com/19d4380804b17d884cbb8ec6c76bd5fdf4ca1d9be55317ba53a9d30111e75e23/68747470733a2f2f692e696d6775722e636f6d2f624e32794b32622e676966)
> 
> hopefully that can be fixed 😄
> 
> Firefox nightly 96.0a1 Organizr 2.1.1140

Please open a new issue instead of commenting a almost year old closed issue

**Comment by jscottelblein** [comment]
@Jerrk Is it only in Firefox?

https://www.reddit.com/r/firefox/comments/7rz9gp/open_a_link_with_mouse_middle_click_opens/

https://stackoverflow.com/q/17094413/553663
