### ISSUE TITLE
How to add meta content noindex?

### ISSUE THREAD

**Issue by fabisiak** [causefx/Organizr#1517]
Hi,
How to add noindex content to configuration?
I know where I can add this to index.php file but probably on next update Organizr I must add this section again.

Thanks for great work!

**Comment by tronyx** [comment]
You would have to add it into your reverse proxy config, IE: for Nginx you could all something like this to the location block you have for Organizr:

`add_header  X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";`

You can read more about the various options for the header [HERE](https://www.searchenginejournal.com/everything-you-need-to-know-about-the-x-robots-tag/314561/#close). You could, instead, add the header within the main `server` block of your config as well so that it is applied to everything.
