### ISSUE TITLE
Emby media link.

### ISSUE THREAD

**Issue by joelang1699** [causefx/Organizr#1564]
Version: 2.1.120
Branch: v2-master
Server OS: *nix
PHP: 7.3.25
Install Type: Official Docker
Auth Type: both
Auth Backend: emby_local
Installed Plugins: 
Installed Themes: 
Theme: Organizr
Local: false
oAuth: false

Clicking the green emby icon just take you to the emby homepage instead of tv show/film in question even if you are already logged into emby.

See img https://i.postimg.cc/nVQLq1CD/Screenshot-2021-01-21-004450.png

**Comment by tronyx** [comment]
You need to inspect the button and see what the URL ends up being, then you need to perform trial and error with the Emby URL you set in Organizr, which is how the URL to open media is determined. There is no one right answer because everyone's setups can be a little different.

**Comment by joelang1699** [comment]
If I change the Emby URL to anything apart from the default WAN/LAN Emby won't connect at all. 

Using Chrome inspection gives a URL of (for example) https://emby.domain.co.uk/web/#!/item/item.html?id=2649128
however in Emby itself the URL is https://emby.domian.co.uk/web/index.html#!/item?id=2649128&serverId=8bb4c473327a44af832d099140c49992

&serverId=8bb4c473327a44af832d099140c49992 seems to be the key here which isn't being added.

Unless I'm missing something?

**Comment by causefx** [comment]
are you on dev or master?

**Comment by tronyx** [comment]
> 
> 
> If I change the Emby URL to anything apart from the default WAN/LAN Emby won't connect at all.
> 
> Using Chrome inspection gives a URL of (for example) https://emby.domain.co.uk/web/#!/item/item.html?id=2649128
> however in Emby itself the URL is https://emby.domian.co.uk/web/index.html#!/item?id=2649128&serverId=8bb4c473327a44af832d099140c49992
> 
> &serverId=8bb4c473327a44af832d099140c49992 seems to be the key here which isn't being added.
> 
> Unless I'm missing something?

Does simply appending the `serverId` bit to the end of the URL allow it to work or do you also need to change `https://emby.domain.co.uk/web/` to `https://emby.domain.co.uk/web/index.html`?

I also see a difference of `#!/item/item.html?id=2649128` and `#1/item?id=2649128` which could matter.

**Comment by joelang1699** [comment]
Appending the URL with &serverId=8bb4c473327a44af832d099140c49992 takes you straight to the item in question

"Does simply appending the serverId bit to the end of the URL allow it to work or do you also need to change https://emby.domain.co.uk/web/ to https://emby.domain.co.uk/web/index.html?"

Entering  https://emby.domain.co.uk/web/ or https://emby.domain.co.uk/web/index.html? in the WAN section just results in being redirected to the Emby landing page when clicking on the icon.

**Comment by joelang1699** [comment]
Master

**Comment by causefx** [comment]
dev has a field where you can enter any format you like now, it will be pushed tomorrow...
![image](https://user-images.githubusercontent.com/16184466/105413503-6c794700-5bf3-11eb-915b-cef7fcffecf9.png)

**Comment by joelang1699** [comment]
Excellent I'll give this a go later today!

**Comment by causefx** [comment]
please re-open if the issue isnt fixed.

**Comment by Starstrike** [comment]
I know this closed over 3 years ago but I'm reopening this issue because this Emby button on the item doesn't do anything from Recently Added. The box just disappears. It doesn't open Emby, doesn't switch to the sidebar tab I've created, nothing.

I'm using the Nord theme, but also tested with the default themes, no difference. I click the item from the Recently Added, click the Emby button, the box disappears. Nothing in the browser console log when that happens either.

![image](https://github.com/causefx/Organizr/assets/1996734/8f40b271-197d-4684-adf4-508ddcab5be6)

The URL it's attempting is what I have in the Misc Options. https://REDACTED.DOMAIN/web/index.html#!/item?id={id}&serverId={serverId}

Let me know what I can get for this. I've tried multiple log levels, nothing shows up in the log when this doesn't work.
