### ISSUE TITLE
Organizr breaks other hosted apps

### ISSUE THREAD

**Issue by bjdutcher** [causefx/Organizr#1653]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
After uninstall using oui, cannot access any previously accessible apps such as radarr and sonarr. 

<hr>

##### Reproduction Steps:
Installed and configured Organizr and then decided didnt like it and uninstalled. Try to open radarr or sonarr in chrome. Can no longer access.

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
How are you trying to access Radarr and Sonarr?  From ip:port? Domain?

If domain, I don't think that will work because:

OWI/OUI installs Organizr, PHP and Nginx
with that being said, I believe...
OWI/OUI uninstalls Organizr, PHP and Nginx

So you will no longer have reverse proxies setup if you configured them using the server block for Organizr.

If you are accessing via ip:port, that has nothing to do with Organizr.

Hope that helps.

**Comment by bjdutcher** [comment]
I use domain:port.

**Comment by causefx** [comment]
Yeah, I don't think the issue is with the installer.  
As you can see in the code: https://github.com/elmerfdz/OrganizrInstaller/blob/master/ubuntu/oui/ou_installer.sh#L550
It uninstalled Nginx - PHP - CertBot
Then it removes these two directories:
```
rm -rf /var/www
rm -rf /etc/letsencrypt
```
If you believe it's still an issue with the uninstaller... Open up an issue on their repo:
https://github.com/elmerfdz/OrganizrInstaller/issues
