### ISSUE TITLE
Using foreign characters for plex tab name like ("Vidéo" instead of "Video") broke link from active stream

### ISSUE THREAD

**Issue by StudioEtrange** [causefx/Organizr#1656]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
* The problem concerns links from plex active stream in homepage to matching video in plex
* Everything is configured including the plex tab name

* What is working : click on an active stream INFO icon, then click on PLEX icon into the popup : **OK** redirect to plex tab onto the matching video
* What is working : click on PLEX icon directly on the active stream : **OK** redirect to plex tab onto the matching video

* What is NOT working : **click on PLEX icon directly on the active stream WHEN PLEX tab name have special characters : KO** nothing happens
* BUT this is working : click on an active stream INFO icon, then click on PLEX icon into the popup WHEN PLEX tab name have special characters : **OK !**

<hr>

##### Reproduction Steps:
Use special characters in plex tab name like french character "Vidéo" 

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
Hmm - will do some testing on this.

**Comment by ChrisYx511** [comment]
Also related to foreign characters, if I try to use Chinese characters in the names of any tab and set the tab to "New Window", it will always point to the URL of the first tab instead of the URL of the actual tab when I click on it. If I only use letters in the alphabet, it works perfectly fine.

See attached steps.
[organizr.zip](https://github.com/causefx/Organizr/files/6542615/organizr.zip)

**Comment by causefx** [comment]
is this fixed for you?
