### ISSUE TITLE
[Request] Seperate auth levels for Jackett widget

### ISSUE THREAD

**Issue by BanditTech** [causefx/Organizr#1675]
But would it be amazing if we could discriminate between users in our jackett search widget. 
allow some users to magnet link/ ddl
and same for blackhole
So instead of just toggling the blackhole link on or off, it would be shown to those above the privilege level

**Comment by angrycuban13** [comment]
Sharing logins is against most tracker rules

**Comment by BanditTech** [comment]
But the jackett widget is already providing the DDL of the torrent by default....? so not sure why you are mentioning that rule.

I just want to make it so that if they are high enough privileges' it also shows the blackhole link. 
Or, maybe the other way around would be better, make one min auth for showing Blackhole, then above another min auth it will also show the DDL link.

So then the users can download files to the server, but authorized users can download the torrent directly.

I just want to be able to leave it configured once without having to change the setting depending on what kind of link I want.

**Comment by angrycuban13** [comment]
> But the jackett widget is already providing the DDL of the torrent by default....? so not sure why you are mentioning that rule.

As the admin you provide the level of access for the homepage items. Just because you set your homepage item access to `User` or `Power User` doesn't mean you're still
not breaking the tracker's rules by allowing people other than yourself to download from it. 

If you aren't actually letting people access your Organizr and use the homepage item to download torrent files then you should reword your original issue

**Comment by BanditTech** [comment]
I just leave it on blackhole, if and when I want the actual DDL link, I change the option for the widget...
I just want admin account to have both links... why is that so taboo

**Comment by causefx** [comment]
this is do-able but please open a feature request @ vote.organizr.app
