### ISSUE TITLE
Pages return ERR_BLOCKED_BY_RESPONSE

### ISSUE THREAD

**Issue by tessierp** [causefx/Organizr#1755]
Hi,

With a few servers I'm running, among them OPNSense, PIHOLE and Proxmox, trying to display the web page will come back with this error : ERR_BLOCKED_BY_RESPONSE .

The only way out of this issue is by displaying the page in a new Window, IFrame just wont work.

**Comment by HalianElf** [comment]
Right, those apps block iframing. Your options are use the new window or use some method to strip the headers that block it out.

**Comment by tessierp** [comment]
Sounds good, I don't mind going with a New Window, the iFrame was a nice to have really.

I did see someone posted on reddit and proposed a solution, a plugin but I wasn't able to find it.

https://www.reddit.com/r/organizr/comments/m066uf/can_no_longer_log_into_https_sites_with_form/

**Comment by HalianElf** [comment]
Updated link for that since the wiki migration is: https://docs.organizr.app/help/faq/login-looping-samesite-errors

But that's a completely separate issue from yours since you can't even get to the login page.

Either way, this isn't an Organizr issue and there's nothing that could be done within the code to get around it.
