### ISSUE TITLE
Tab names 

### ISSUE THREAD

**Issue by brandonhowlett** [causefx/Organizr#1885]
###### Operating System: Docker
<hr>

##### Problem Description:

Setting a tab name with two or more spaces results in one hyphen followed by encoded spaces. E.g., https://domain.com/#Plex-Media%20Player
<hr>

##### Reproduction Steps:

Create a tab name with two or more spaces
<hr>

#### Errors on screen?  If so paste here:

```
None
```

**Comment by causefx** [comment]
fixed in dev - thanks!

**Comment by Banakayou** [comment]
hello,
I just would like to report a small bug that I think is due to this fix that was introduced in the latest update.
Tabs now correctly display "-" instead of "%20" in the url but when I hit refresh (F5) it redirects me to my default tab. Only when tab name contains 2 or more spaces though.
thank you :)

**Comment by causefx** [comment]
i'll check this out.

**Comment by causefx** [comment]
fixed
