### ISSUE TITLE
[FR] Grouped Tabs

### ISSUE THREAD

**Issue by CBers** [causefx/Organizr#271]
I look after 6 PCs for friends and family and I have a bookmark for each of their services. 

I don't want to add all of these to Organizr as there would be too many tabs down the left, so I was thinking for each PC I manage, there would have a group of tabs, which when opened, it shows the tabs for that PC.

Thanks.

**Comment by causefx** [comment]
this is still planned

**Comment by CBers** [comment]
OK, thanks causefx.
I couldn't find any reference to it, so i thought I'd raise an FR.

**Comment by Cerothen** [comment]
This will be a V2.0 item

**Comment by CBers** [comment]
OK, thanks.

**Comment by mrwebsmith** [comment]
i know this is planned and hopefully as such is still in the "Design" phase.. can i request a slightly different use case to be considered... instead of different pcs to group by, let us group tabs by whatever/manually.. so i can group by "type" of thing...  "downloader client app" vs "media management app" vs "other" vs "Work apps"... etcetc

**Comment by Cerothen** [comment]
@mrwebsmith That is how it always would have been. Its actually less effort for us to make the grouping user configured than to somehow figure out what criteria should be used to establish a group.

**Comment by causefx** [comment]
this will be implemented in 2.0, if you have more FR, please post on http://feathub.com/causefx/Organizr
