### ISSUE TITLE
HTTPS vs HTTP

### ISSUE THREAD

**Issue by davidszerman** [causefx/Organizr#272]
Hi,

when I try to access pages with https such as gmail,... it fails ; I understand the issue is related to the fact that my website is not accessed via a secure web url 

What would be the best way to manage that ?

Add https certificate to this site ? In that case is it possible to access non http websites ?

Any setting to change in the app Organizr in order to bypass this ?

Thanks for this great tool !

**Comment by elmerfdz** [comment]
1. You can view HTTPS sites on HTTP websites but you can't view HTTP or mixed content on a HTTPS enabled website. If you add a HTTP site on your secured HTTPS enabled site then it will just give you a blank page with a warning on the address bar (chrome). 
![image](https://cloud.githubusercontent.com/assets/22656503/25005553/4d40dc40-2051-11e7-8d4d-500df1b76b95.png)

- You can enable the unsecure content but that would breal the HTTPS session and will no longer be secured.
![image](https://cloud.githubusercontent.com/assets/22656503/25005707/dc2db680-2051-11e7-991b-0f21273dab2f.png)

![image](https://cloud.githubusercontent.com/assets/22656503/25005728/eee15f2a-2051-11e7-9188-bd0424bc71b9.png)


2. You can't view gmail because it blocks iFrames, all google site do I think.

![image](https://cloud.githubusercontent.com/assets/22656503/25005403/c193aae2-2050-11e7-90ce-f8651f108962.png)

3. You should probably setup HTTPS on your website. The complexity on achieving that is based on your OS and the solution you choose. Look into Letsencrypt or Cloudflare or maybe someone here can suggest you a different solution.

**Comment by davidszerman** [comment]
Hi, 

Thanks, actually, the error was not linked to the https issue but, indeed, to X-Frame-Options and so on... Grrrr...

**Comment by causefx** [comment]
Install the xframe plugin, in the help section

**Comment by davidszerman** [comment]
It is magic ! Great ! Thanks
