### ISSUE TITLE
Cache issues on Radarr

### ISSUE THREAD

**Issue by Ninjouz** [causefx/Organizr#275]
Hey guys,

There is some cache issues on Radarr, like a movie is downloaded then moved by it but the status stays as Missing.

If I load the Radarr homepage directly on the same browser, it shows "Downloaded".
I have to SHIFT-F5 to get Organizr to refresh and bypass the cache.

**Comment by causefx** [comment]
is this on homepage? or having Radarr in a tab?

**Comment by Ninjouz** [comment]
Radarr in an Organizr tab => cache issues
Radarr direct => no issue

**Comment by causefx** [comment]
Hmmmm. First I'm hearing of this. I'll look into it

**Comment by dejected1** [comment]
Not sure if this is related or not. Within radarr: when adding a movie from a list it always defaults to the local computer directory of the computer i'm on instead of the network path of my network. Example: \\myserver\movies\new\ is the path but when adding the movie radarr makes it c:\windows\system32\movie name\. When accessing radarr directly remotely it doesn't seem to have an issue, only from organizr. also when adding a move manually and choosing the network path seems to work. Only when adding movies automatically does it crap out.

**Comment by Ninjouz** [comment]
Dont think so, everything the same for me. Organizr is hosted on the same server as Radarr / Sonarr etc.
Radarr is proxied through Apache httpd and Organizr served by the same httpd.

It's just cache issues like expiry date or something.

**Comment by causefx** [comment]
this should be fine now
