### ISSUE TITLE
Bug: Seamless login

### ISSUE THREAD

**Issue by untotren** [causefx/Organizr#306]
I am confused, it is not logging into obmi and emby automatically?  Is there a setting I need to enable?  I just want it to pass the username+password to all services.

**Comment by Cerothen** [comment]
This is not a bug, it is simply not supported on those platforms. If you want to have these features you could add a post to show support for it at the following links.

https://emby.media/community/index.php?/topic/46635-support-for-logging-users-in-though-url-scheme/

https://github.com/tidusjar/Ombi/issues/1360

**Comment by untotren** [comment]
You're telling me there's no possible way to store the username+pass temporarily for the users in the session then have javascript target username+password fields for each service?

**Comment by Cerothen** [comment]
If it's basic authentication you can use the following URL syntax.

Https://user:pass@host.tld

It might be possible also if everything is served from the same host otherwise browser security would make it impossible.

Considering this it would be a crap ton of work and we would get an ocean of questions related to setting up the proper proxy features. That being said it is something that I would also like, from a perspective of scalability though it's best if those services support url based logins over complicated workarounds.

Who knows though, we are putting the roadmap together for 2.0, anything is possible

**Comment by untotren** [comment]
I think this would be awesome.  Because as of now it seems the login is pointless.  It is only security by obscurity.

**Comment by shadowswan** [comment]
This is supported in ombi v3 according to this

https://github.com/tidusjar/Ombi/issues/1360

Will this be supported in Organizr?

**Comment by causefx** [comment]
Yes, we will add that as soon as Ombi is stable.
