### ISSUE TITLE
FR: Notification on tabs

### ISSUE THREAD

**Issue by untotren** [causefx/Organizr#314]
When a tab has an active notification, like a new movie, etc, make the tab blink or have a small red dot, etc.  My main driver behind this is the desire to implement a chat, and it would show activity when a message is received.

**Comment by Cerothen** [comment]
This will likely never happen, due to JavaScript security if you don't serve everything from the exact same hostname and port then it will not allow access to anything in an iframe. Then every single thing you have in a tab would also have it's own implemention of a notification system.

It's unfortunately to much work for the narrow circumstance that it could be used.

**Comment by untotren** [comment]
No way?  Chrome has the notification when you get a facebookmessage, is there something similar that culd be hooked?

**Comment by Cerothen** [comment]
It's not something that I can see myself spending time on, sorry, just being up front about it. Unless @causefx wants to work on it or some other person wants to contribute to the code via a pull request I don't see this item being implemented.

In terms of facebook sending a message to chrome that isnt the same thing. its interacting with the browser not another site.

**Comment by untotren** [comment]
@Cerothen ty for the honesty :)
