### ISSUE TITLE
Google Calendar on the homepage or in tabs

### ISSUE THREAD

**Issue by kevinb77** [causefx/Organizr#573]
Has anyone been able to get the Google Calendar website in a tab or on their homepage?

**Comment by causefx** [comment]
I maybe be able to code in google calendar feeds.

**Comment by kevinb77** [comment]
That would be amazing! I would love too have GCal integrated right into the already existing cal provided by Sonarr and Radarr

**Comment by causefx** [comment]
does anyone have a link for me to try?

**Comment by k2trf** [comment]
GamingOnLinux has an ical through Google Calendar, to track all known games releasing that have Linux clients upcoming.

https://www.gamingonlinux.com/calendar_ical.php
The Calendar ID is nl09amnod2utqd0fhjcivda9cetb6rll@import.calendar.google.com

They make this publicly RO, so I'd imagine it'd be a decent test -- December or September would be better months to use since game launches trickly off during this time of year.

**Comment by causefx** [comment]
with the way we went with calendar not sure this is possible now.
