### ISSUE TITLE
[Feature Request] Disable top bar

### ISSUE THREAD

**Issue by joshuaavalon** [causefx/Organizr#669]
Most of the web app now have a top bar. Combine with Organizr often seems weird. It would be nice if you can disable the top bar. May be you can do it in CSS but I am not an expert on that.

I have create some draft using photoshop. The top bar is only use for show Organizr and user icon. May be we can move them to side bar?

![](https://user-images.githubusercontent.com/7152420/31585143-41488764-b1ef-11e7-9bee-098b64ec7135.png)
![](https://user-images.githubusercontent.com/7152420/31585144-4240c118-b1ef-11e7-93ce-2daee3e717ad.png)

**Comment by dejected1** [comment]
i like this idea. i cant tell you how many new users to the server ignore the ombi landing page for login and click on the "login" button on the top bar. Then i get emails wondering why its not working. having a choice to move it would be great.

**Comment by causefx** [comment]
good idea

**Comment by chasgames** [comment]
I like this idea also

**Comment by jonfinley** [comment]
I️ like this as well

**Comment by oidz1234** [comment]
me too :D \o/ 💯 💯 💯

**Comment by jaydee99** [comment]
me too !

**Comment by Skaronator** [comment]
Has this been addressed in v2? Or why is this issue closed?

**Comment by Skaronator** [comment]
Ah okay. Thanks for the quick response.

Is there a way to remove the top bar completly and move the account menu from the top right to the buttom left (sidebar menu).

**Comment by causefx** [comment]
Would have to be custom css and js. I will be adding custom js soon

**Comment by cbartondock** [comment]
There is a collection of custom themes that does exactly this and does it well:

https://github.com/Archmonger/Blackberry-Themes

Whatever they are doing could definitely be added as an option in customization settings.

**Comment by toxic0berliner** [comment]
Don't know if you're still interested, but I'm new to organizr, was not willing to fuss around with themes and nginx proxying my stuff, I'm already using traefik... So I found a quick and dirty CSS trick, sharing here in case someone wants it : 

```
#body-index {
    padding-top: 0px !important;"
}
#gn-menu {
    width:50px !important;
}
.top-clock, .pull-right {
    display:none !important;
}

```
To be added in Settings>Colors>CustomCSS on organizr v1. Will look at organizr v2 soon.

It's still a bit ugly when you open the burger menu, but it does the job fine for me, granting me back these costly vertical pixels on nowerday's 16:9 displays...


EDIT : sorry for the false hope, as it turns out this change only moves the bar to the bottom, actually the bar is hiddent, but the function calculating the height of the content thing is not aware of that... Too bad, it's not that simple.

**Comment by yblis** [comment]
add this custom css if you want to display topbar on mobile and hide on computer:

```
@media (min-width: 767px) {
    .navbar-static-top{
    display: none;
}

#page-wrapper, .iframe {
    height: 100vh;
    margin-top: 0 !important;
}

#editHomepageItemDiv {
    top: 0 !important;
}
}
```
