### ISSUE TITLE
Organizr does not honor referred host:port

### ISSUE THREAD

**Issue by chrisblach** [causefx/Organizr#761]
Organizr Version: V 1.7
Branch: Master
WebSever: Nginx
Operating System: FreeBSD
<hr>

Problem Description:

My Nginx listens on port 80, but for specific reasons, instead of forwarding 80, I have port 80 mapped to an external port of let's say 1234. When hitting my server from outside my network I use EXTERNAL_IP:1234 which maps to INTERNAL_IP:80 reaching the nginx which takes care of the routing.

In nginx config I have for example this for plex:

```
location /web/ {
            proxy_pass http://INTERNAL_IP:32400;
	    proxy_redirect off;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       	}
```
When I hit EXTERNAL_IP:1234/web in Chrome it successfully reaches plex. When I click the Plex tab in my Organizr it shows this in the request:

```
Request URL: http://EXTERNAL_IP:1234/web
Request Method :GET
Status Code: 301 Moved Permanently
Remote Address: EXTERNAL_IP:1234
Referrer Policy: no-referrer-when-downgrade

Response Headers:
Connection:keep-alive
Content-Length:185
Content-Type:text/html
Date:Sun, 07 Jan 2018 22:47:35 GMT
Location: http://EXTERNAL_IP/web/
Server: nginx/1.12.2
```
It redirects my request to port 80, not honoring that my request came from 1234, getting a timeout as 80 is not exposed.

As far as I can tell this has to be a problem with Organizr as I can reach my routes directly. Am I missing something?

**Comment by causefx** [comment]
Is this in the tab URL or homepage?

On Jan 07, 2018, at 03:55 PM, chrisblach <notifications@github.com> wrote:

Organizr Version: V 1.7
Branch: Master
WebSever: Nginx
Operating System: FreeBSD

Problem Description:

My Nginx listens on port 80, but for specific reasons, instead of forwarding 80, I have port 80 mapped to an external port of let's say 1234. When hitting my server from outside my network I use EXTERNAL_IP:1234 which maps to INTERNAL_IP:80 reaching the nginx which takes care of the routing.

In nginx config I have for example this for plex:

location /web/ {
            proxy_pass http://INTERNAL_IP:32400;
	    proxy_redirect off;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       	}
When I hit EXTERNAL_IP:1234/web in Chrome it successfully reaches plex. When I click the Plex tab in my Organizr it shows this in the request:

Request URL: http://EXTERNAL_IP:1234/web
Request Method :GET
Status Code: 301 Moved Permanently
Remote Address: EXTERNAL_IP:1234
Referrer Policy: no-referrer-when-downgrade

Response Headers:
Connection:keep-alive
Content-Length:185
Content-Type:text/html
Date:Sun, 07 Jan 2018 22:47:35 GMT
Location: http://EXTERNAL_IP/web/
Server: nginx/1.12.2
It redirects my request to port 80, not honoring that my request came from 1234, getting a timeout as 80 is not exposed.

As far as I can tell this has to be a problem with Organizr as I can reach my routes directly. Am I missing something?

**Comment by chrisblach** [comment]
This is in the tab URL. I have the URL set to /web which it properly tries to hit http://EXTERNAL_IP:1234/web but always gets redirected to port 80 instead.

**Comment by si0972** [comment]
Try adding a trailing slash in the tab url from `/web` to `/web/`

**Comment by chrisblach** [comment]
That worked! Not sure why that would make a difference, but at least it works. Thanks guys!
