### ISSUE TITLE
[Request] Group functionality

### ISSUE THREAD

**Issue by elRadix** [causefx/Organizr#80]
@causefx 

Can you add a group functionality like iDash? 

Is this planned?

Thanks.

**Comment by causefx** [comment]
not sure if i will, is it because you have a lot of tabs, or just want them separated?

**Comment by ianc125** [comment]
I second this request.

I would love to have user roles/groups and then have tabs visible based on the user role/group.
Not only would I switch this out with my crappy muximux setup, but I would love to set this up in a corporate environment as an easy way to setup regularly used web services for our internal users but i would need groups so that only certain users can see links to certain pages.

Awesome job on this btw i have been looking for a nicer alternative to muximux for a whilefor my htpc setup and never found you until now.


Not that you would want to but I could easily see you marketing a version of this current setup with Active Directory integration to corporate customers.

**Comment by causefx** [comment]
i have thought about that.  It is certainly in the back of my mind.  I will let you know if I start to pull the trigger on this.

**Comment by ianc125** [comment]
Yah definitly let me know if you work on it. I can have our company throw
you a donation for you work.

Thanks

**Comment by causefx** [comment]
No donations buddy. Everything is always free. :)

**Comment by causefx** [comment]
this will be implemented in 2.0, if you have more FR, please post on http://feathub.com/causefx/Organizr
