### ISSUE TITLE
Org v2 - UI suggestions to make it perfect

### ISSUE THREAD

**Issue by jaydee99** [causefx/Organizr#807]
Hi,

After a few days using v2, i have to say that i really like it, you guys did an amazing work. But some details in the UI could be better and for the moment i'll stick with v1 because of those

- On Login screen, logo is appearing twice (on top and on right side) which looks weird,
- Top bar size is really too big and takes too much space on the screen. Option to make it smaller, and better, to make it disappear would be really great,
- Left bar for tabs navigation : icons are bigger than on v1, spaces between icons too, and i can't see all of them on my screen (i could with v1)
- Title bar for homepage items is really too big also, i don't really like that flashy blue color also but i guess customize options are going to come

I know that thread doesn't belong to issues but i didn't know where to post that...

Thanx guys for your work !

**Comment by causefx** [comment]
- Will have to check the consensus on this one

- Will look into this one

- Can look into the spacing, I thought i made the icons the same size

- Colors will be changable by theme or custom css soon

**Comment by jaydee99** [comment]
Thanx !!

**Comment by causefx** [comment]
FYI, 3rd one is done

**Comment by dimitrijp** [comment]
sorry for hijacking this one..not to open additional...i gave organizr v2 test drive and few items for improvement I see (but everyone has different eyes :) )
- login page
I think there is too much options presented multiple times. Right navigation pane is not really useful since by default you are presented with login page..also another option to choose login is right top corner. - suggestion to ditch navigation pane from login page completely. 
Top bar is presented with host name / logo basically having it twice as already noted by jaydee99

- Tab Editor - Homepage Items  - maybe make icons smaller, currently really looking big ? ?
 -Plugins - mailer and speedtest icons are different size currently
- Image manager - freenas icon is not visible loading on the page.

No other issues at the moment..will do more testing..excellent work causefx, thanks for doing this.

**Comment by dimitrijp** [comment]
for the login page .. i mixed left and right :) sorry..what i meant was left side navigation pane. Made a screenshot..with 3 different options to login..first is the left pane..this i personally don't find useful..right is cool, and also needed for mobile..then 3 option is to click on top right Guest - again Login option.

https://imgur.com/BmZW3ub

Regarding the image for freenas-logo..i change the theme to dark and its working..but on withe is empty space...screenshot attached.

https://imgur.com/a/Tr5nagh

**Comment by dimitrijp** [comment]
latest beta .. icon sizes of plugins are still different (this is inactive plugins tab)

![plugins](https://user-images.githubusercontent.com/32590776/39670737-5c78aba2-510b-11e8-8016-51d9519d8bab.jpg)

**Comment by causefx** [comment]
All suggestions are completed minus the 2nd one, i will revisit that later in beta.  For now if people want it, request at feathub plz
