### ISSUE TITLE
[Feature Request] Pin Open menu

### ISSUE THREAD

**Issue by mrdeadlocked** [causefx/Organizr#90]
Would it be possible to have the side menu be able to be pinned open. I would like a view to always be showing that shows the full labels not just the icons.

**Comment by causefx** [comment]
hmmmm, didnt think anyone would have wanted that.  not a bad suggestion, I will look at this tonight.

**Comment by mrdeadlocked** [comment]
It would just help for a couple cases where people do not know/use the menu as much. Seeing the labels they would then not have to click thru icons.

**Comment by causefx** [comment]
Yeah, I hear you. Lets see how much editing that would be haha.

**Comment by causefx** [comment]
Alright, So I worked on this for a little while and as I was doing it, it would require me to re-write the entire menu because it is based all around having it closed while browsing.  I may look into this again down the road but I really need to focus on getting the rest of the items done.  I will be closing this for now but will certainly be keeping this in the back of my mind.
