### ISSUE TITLE
[v2] CookiePassword missing

### ISSUE THREAD

**Issue by rix1337** [causefx/Organizr#948]
###### Operating System: Docker Image
<hr>

##### Problem Description:
I am still running v1 of Organzir. My main use case is being able to secure my various reverse proxied apps with the cookiepassword option. This is extremely convenient while also secure.
<hr>

##### Reproduction Steps:

Try to recreate v1 config with a cookiepassword.
<hr>

#### Errors on screen?  If so paste here:

```
None
```

Would you be able to provide a quick and dirty plugin/fix that allows setting the cookiepassword next to a group/user?

PS: I love v1 of Organizr, but you have outdone yourself with v2. It looks and feels so much better.

**Comment by rix1337** [comment]
Sorry, am an idiot. The wiki is very clear how to do this.

**Comment by causefx** [comment]
awesome.  lemme know if u need help.

**Comment by nurse-curtis** [comment]
I just upgraded to v2 and otherwise, everything is working great.  The problem is that given my setup:

Internet -> HAProxy on pfSense -> Debian Stretch with Nginx
                                |-> Sonarr, etc.

HAProxy directly proxies all of the services that are linked within Organizr so the best, and currently it seems my only, option for authentication on the frontend was by having Organizr set a cookie password, then HAProxy will only serve the other backend services (Sonarr, Sabnzbd, etc) when the login cookie is present.

Unfortunately, I'm not able to get https://github.com/TimWolla/haproxy-auth-request working with pfSense 2.4 and the Lua 5.3 that comes with it. I suspect I'm the only one missing it though..
